### ISSUE TITLE
Categories for blocks

### ISSUE THREAD

**Issue by believe2013** [werty1001/bemgo#1]
How to organize the arrangement of blocks by categories, when many blocks?

**Comment by werty1001** [comment]
Hi. Categories not support, but you can use redefinition levels for organize, when many blocks.

**Comment by believe2013** [comment]
Thanks for the quick response. Then which command to add the block is not "mainLevel" (to other levels)?

**Comment by werty1001** [comment]
Sorry, it is possible only for main level, for another levels only by hand
