### ISSUE TITLE
Как динамически менять классы (переиспользовать блок)

### ISSUE THREAD

**Issue by karpov2** [werty1001/bemgo#10]
Скажите плз, как можно при переиспользовании блока, при этом динамически менять классы (элементы и модификаторы)

Вот пример https://prnt.sc/qhlo1j

----------------------------------------------------------------

Есть блок logo который мне нужен в header и footer 

```
<a href="#" class="logo">
    <svg class="logo__image @@element">
        <use xlink:href="@symbol#logo__logotype"></use>
    </svg>
</a>
```

Когда блок logo использую в блоке header - мне нужно добавить ему например элемент или модификатор блока header

```
<header class="header">
	@@include('develop/logo/logo.html', {
		  "element": "header__logo"
	})
</header>
```

А когда блок logo использую в блоке footer - мне нужно добавить ему элемент или модификатор блока footer

```
<footer class="footer">
	@@include('develop/logo/logo.html', {
		  "element": "header__logo"
	})
</footer>
```

Вот я реализовал - https://prnt.sc/qhltzy (папка dist)
Вроде норм - когда я указываю класс (когда он точно должен быть)

----------------------------------------------------------------

А если я не добавляю вообще классов, что бы @@element (передаваемый класс) - не тянулся в dist

Но когда я не передаю класс - в dist уходит @@element и создается папка (блок)
пример: https://prnt.sc/qhlvi4

----------------------------------------------------------------

Или если мне не нужен класс - мне нужно передавать пустую строку?
пример: https://prnt.sc/qhlx17

```
<footer class="footer">
	@@include('develop/logo/logo.html', {
		  "element": ""
	})
</footer>
```

----------------------------------------------------------------

Как то другим способом можно такое реализовать?

**Comment by werty1001** [comment]
Только с помощью пустой строки, для более гибкого поведения уже нужно использовать шаблонизаторы.
