### ISSUE TITLE
SCSS

### ISSUE THREAD

**Issue by AkanoCA** [werty1001/bemgo#12]
Доброго времени суток

Пытаюсь подключить SASS, но, к сожалению у меня что-то не выходит.

Я прописал в config.js следующее:

`use: {
        ...
	styles: '.scss',
},`

И после npm start все запускается.
Далее, когда я задаю стили ничего не происходит.
И когда сбрасываю терминал и снова пытаюсь запустить через npm start, то в консоли появляется ошибка

![image](https://user-images.githubusercontent.com/55537294/73545018-7a1a4780-444b-11ea-8fd0-5409d69f2bd5.png)

debug.log 
![image](https://user-images.githubusercontent.com/55537294/73545225-f9a81680-444b-11ea-80d0-a48c4874dc28.png)

И что интересно, и наверное, закономерно, если я удаляю scss файл из проекта, то запуск проходит нормально
Или же, когда я меняю styles: '.sass' или '.css'
При этом, если я создам файл sass при style: '.sass', то все тоже самое, что и с scss

Помогите, пожалуйста, разобраться :с

[dev_Demo[2020-01-31__16-46].zip](https://github.com/werty1001/bemgo/files/4139656/dev_Demo.2020-01-31__16-46.zip)

**Comment by werty1001** [comment]
Попробуйте переустановить модуль `npm rebuild node-sass --force`

**Comment by AkanoCA** [comment]
К сожалению, ничего не изменилось..

**Comment by AkanoCA** [comment]
Помогла просто установка node-sass... /фейспалм/
Спасибо большое, Вы мне помогли разобраться
