### ISSUE TITLE
Мне нужно добавить видео к проекту (файл локально), но сборщик игнорирует файл  mp4

### ISSUE THREAD

**Issue by yurii-kdz** [werty1001/bemgo#14]

**Comment by yurii-kdz** [comment]
Мне нужно добавить видео к проекту (файл локально), но сборщик игнорирует файл mp4

Подскажите, как это исправить?

**Comment by werty1001** [comment]
Здравствуйте, в каком виде вы вставляете видео?

В HTML нужно добавить разметку и указать источник (блок, где лежит видео), например для блока **app** (видео должно лежать тут - blocks/develop/app/assets/greeting.mp4)
```
<video controls="controls">
  <source src="@app/greeting.mp4" type="video/mp4">
</video>
```
