### ISSUE TITLE
Auto create file with .pug template

### ISSUE THREAD

**Issue by hoainam12k** [werty1001/bemgo#2]
Hi,
If I config:
```
use: {
	templates: '.pug',
	scripts: '.js',
	styles: '.scss',
},
```
It will not create Element scss file when I save .pug file. Only work with .html
Do you have any suggestion?

Thank you for great tool!

**Comment by werty1001** [comment]
Hi, please show yours **autoCreate** option from app/config.js

**Comment by hoainam12k** [comment]
here is it:

```
autoCreate: {
	onlyOnWatch: true,
	folders: ['assets'],
	files: [ '.scss' ],
	levels: [ 'develop' ],
	ignoreNodes: [ 'symbol', /_no_js/i ],
},
```

I tested [your app here](https://github.com/werty1001/app) but it did not create too.

**Comment by werty1001** [comment]
@hoainam12k, you tested it on windows or another os?

**Comment by hoainam12k** [comment]
on Mac OS 10.14.4, node v8.11.1

**Comment by werty1001** [comment]
@hoainam12k, try `npm run add mytest[.scss,.js,.pug,.json]`, it not working too?

<img width="455" alt="mytest" src="https://user-images.githubusercontent.com/6961502/56848314-0bbebc80-68f0-11e9-9afa-50ba7f7d9bc4.png">

**Comment by hoainam12k** [comment]
it works well, created folder and 4 files

**Comment by hoainam12k** [comment]
should I note anything when write mixin in blocks?

**Comment by werty1001** [comment]
It strange, please, show .pug file.

> should I note anything when write mixin in blocks?

No

**Comment by hoainam12k** [comment]
my bad. It will not create if I save component.
It creates files when I save index.pug file.

Thank you!
