### ISSUE TITLE
Слэш в CSS меняется на обратный слэш

### ISSUE THREAD

**Issue by Vallek** [werty1001/bemgo#3]
После сборки знаки косой черты в путях внутри url() меняются на обратную косую черту. В результате пути не работают.

**Comment by werty1001** [comment]
Какая ос? Есть возможность запилить демку?

**Comment by Vallek** [comment]
Windows 7, 64bit. Что подразумевается под демкой?

**Comment by werty1001** [comment]
> Что подразумевается под демкой?

Слепок сборки `npm run zip:dev`

**Comment by Vallek** [comment]
Не хотелось бы этот код отправлять и разбираться в еще одном инструменте сейчас не готов наверно. А предположений из-за чего это может быть нет?

**Comment by werty1001** [comment]
> Не хотелось бы этот код отправлять и разбиратсья в еще одном инстурменте сейчас не готов наверно.

Каком инструменте? Это команда встроена в сборку. Можете оставить только фрагмент (блок) с ошибкой.

> А предположений из-за чего это может быть нет?

Это из-за винды и ее особенностей.

**Comment by Vallek** [comment]
[dev_Demo[2019-09-04__18-08].zip](https://github.com/werty1001/bemgo/files/3575180/dev_Demo.2019-09-04__18-08.zip)

Вот сделал на тестовом html, там результат тот же. Не очень понял, чем вам это поможет, если дело в винде, но окей. Еще пробовал с дефолтным конфигом, но я и так там особо ничего не менял вроде.

**Comment by werty1001** [comment]
Спасибо за обращение, должно теперь норм работать.
