### ISSUE TITLE
Приветствую, а как подключить шрифты локально?

### ISSUE THREAD

**Issue by aleksandrweb** [werty1001/bemgo#5]

**Comment by werty1001** [comment]
Здравствуйте, создайте папку fonts (например в корневом блоке), поместите туда шрифты и подключите их в стиле

**Comment by aleksandrweb** [comment]
О отлично, заработало) теперь другой момент, переменные sass не хотят работать,
файл с переменными подключаю глобально globalStyles: ['app/blocks/develop/app/base/base.sass'],
выдает такую ошибку
PluginError: base\base.sass
Error: Invalid CSS after "      $yell": expected 1 selector or at-rule, was ": #f8c218"
        on line 2 of base/base.sass
        from line 1 of app/blocks/develop/app/app.sass
>>      $yell: #f8c218
   -^

    at options.error (E:\WorkSite\Work\eurotracks.ru\_ver\node_modules\node-sass\lib\index.js:291:26) {
  status: 1,
  file: 'base/base.sass',
  line: 2,
  column: 2,
  message: 'base\\base.sass\n' +
    'Error: Invalid CSS after "\t$yell": expected 1 selector or at-rule, was ": #f8c218"\n' +
    '        on line 2 of base/base.sass\n' +
    '        from line 1 of app/blocks/develop/app/app.sass\n' +
    '>> \t$yell: #f8c218\r\n' +
    '   -^\n',
  formatted: 'Error: Invalid CSS after "\t$yell": expected 1 selector or at-rule, was ": #f8c218"\n' +
    '        on line 2 of base/base.sass\n' +
    '        from line 1 of app/blocks/develop/app/app.sass\n' +
    '>> \t$yell: #f8c218\r\n' +
    '   -^\n',
  messageFormatted: '\u001b[4mbase\\base.sass\u001b[24m\n' +
    'Error: Invalid CSS after "\t$yell": expected 1 selector or at-rule, was ": #f8c218"\n' +
    '        on line 2 of base/base.sass\n' +
    '        from line 1 of app/blocks/develop/app/app.sass\n' +
    '>> \t$yell: #f8c218\r\n' +
    '   -^\n',
  messageOriginal: 'Invalid CSS after "\t$yell": expected 1 selector or at-rule, was ": #f8c218"',
  relativePath: 'base\\base.sass',
  name: 'Error',
  stack: 'Error: base\\base.sass\n' +
    'Error: Invalid CSS after "\t$yell": expected 1 selector or at-rule, was ": #f8c218"\n' +
    '        on line 2 of base/base.sass\n' +
    '        from line 1 of app/blocks/develop/app/app.sass\n' +
    '>> \t$yell: #f8c218\r\n' +
    '   -^\n' +
    '\n' +
    '    at options.error (E:\\WorkSite\\Work\\eurotracks.ru\\_ver\\node_modules\\node-sass\\lib\\index.js:291:26)',
  __safety: undefined,
  _stack: undefined,
  plugin: 'gulp-sass',
  showProperties: true,
  showStack: false
}
сами переменные вот
$black: #2c2c2c
$yell: #f8c218
$text: #515151
$white:#fff

**Comment by werty1001** [comment]
Нужно добавить точку с запятой в файле с переменными.
```
$black: #2c2c2c;
$yell: #f8c218;
$text: #515151;
$white: #fff;
```

**Comment by aleksandrweb** [comment]
Помогло, большое спасибо!
