### ISSUE TITLE
Не создает и не подключает бандлы для больше, чем 2-х старниц

### ISSUE THREAD

**Issue by DonTsipa** [werty1001/bemgo#6]
Используя pug при создании в pages больше, чем 2-х шаблонов вовсе не компилит стили и скрипты

**Comment by werty1001** [comment]
Здравствуйте, какая у вас ос? Есть возможность залить слепок? `npm run zip:dev`

**Comment by DonTsipa** [comment]
Windows 10
[dev_Demo[2019-12-23__18-01].zip](https://github.com/werty1001/bemgo/files/3995354/dev_Demo.2019-12-23__18-01.zip)

в pages 2/4 файлов закомментированы, чтобы сборка работала

**Comment by werty1001** [comment]
Спасибо за обращение, проблема была в node-sass плагине, мой последний коммит https://github.com/werty1001/bemgo/commit/f5e3aa1cd6a72e46510c5111a936b5d133ad54fd должен решить проблему.

**Comment by DonTsipa** [comment]
Спасибо большое! Теперь отлично собирает)
