### ISSUE TITLE
Выходит ошибка при долгом описании стилей

### ISSUE THREAD

**Issue by karpov2** [werty1001/bemgo#7]
> Starting 'compile:styles'... PluginError [CssSyntaxError]:  C:\Users\kotki\Documents\Development\Project\BEMGO\app\blocks\develop\header\header__desc.css:4:5: Unknown word

Когда начинаешь писать .css стили и на 1 сек зависнешь) например начинаешь вводить line- (я завис, думаю что дальше писать) и выходит ошибка "CssSyntaxError"
А когда быстро все делаешь - норм работает) 

Просто в код прилетает корявый стиль (типо такого)
`.header__desc {
    font-size: 1.5em;
    line-
    color: #fff;
}`
И watch падает

лог ошибок прилагаю
[лог ошибок.txt](https://github.com/werty1001/bemgo/files/3998959/default.txt)

Помогите плз с решением

**Comment by werty1001** [comment]
Здравствуйте, я так понимаю у вас автосохранение?

**Comment by karpov2** [comment]
да, из-за этого проблема?
сейчас проверю

**Comment by karpov2** [comment]
Все верно) проблема решилась, спасибо
