### ISSUE TITLE
Не работает autoCreate (игнор модификаторов)

### ISSUE THREAD

**Issue by karpov2** [werty1001/bemgo#9]
Я как в документации добавляю строчку игнорирования создание модификаторов

> ignoreStyle: [ /(_|--)[\w]/i ], // игнорируем модификаторы при создании стилей

Но у меня блокируется вообще все автоматическое создание файлов (блоки, елементы)

Мой autoCreate в config.js стандартный (при клонировании), добавил в него 1 строчку ignoreStyle для модификаторов
```
autoCreate: {
	onlyOnWatch: true,
	files: [ '.css' ],
	levels: [ 'develop' ],
	ignoreNodes: [ 'symbol', /_no_js/i ],
	// ignoreStyle: [ /_[\w]/i ], // игнорируем модификаторы при создании стилей
},
```

Я через неделю начну изучать регулярку (может придет понимание), но сейчас не могу понять как решить данный вопрос, подскажи плз

**Comment by werty1001** [comment]
Спасибо, в доках была неправильная регулярка для модификаторов, поправил.

**Comment by karpov2** [comment]
спасибо
